---
- name: Set up the LEMP stack and WordPress for HA && load balancer
  hosts: all
  become: yes
  roles:
    - mariadb
    - nginx
    - php-fpm
    - wordpress
    - keepalived 

  handlers:
    - name: restart mariadb
      service:
        name: mariadb
        state: restarted

    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded
     
     
    - name: Restart PHP-FPM
      systemd:
        name: php-fpm
        state: restarted


    - name: Reload Keepalived
      systemd:
        name: keepalived
        state: reloaded
