---
# roles/wordpress/tasks/main.yml

- name: Ensure /var/www/ directory exists
  file:
    path: /var/www/
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes

- name: Set up wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
  notify:
    - Restart PHP-FPM


