---

- name: Add Elasticsearch GPG key

  rpm_key:

    state: present

    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch


- name: Create Elasticsearch repo file

  copy:

    dest: /etc/yum.repos.d/elasticsearch.repo

    content: |

      [elasticsearch-7.x]

      name=Elasticsearch repository for 7.x packages

      baseurl=https://artifacts.elastic.co/packages/7.x/yum

      gpgcheck=1

      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch

      enabled=1

      autorefresh=1

      type=rpm-md


- name: Install Elasticsearch

  yum:

    name: elasticsearch

    state: present


- name: Configure Elasticsearch

  template:

    src: elasticsearch.yml.j2

    dest: /etc/elasticsearch/elasticsearch.yml


- name: Enable and start Elasticsearch

  systemd:

    name: elasticsearch

    enabled: yes

    state: started

