---
- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Configure Nginx for WordPress and load balancing
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart Nginx

- name: Deploy WordPress Nginx config
  template:
    src: wordpress.conf.j2
    dest: /etc/nginx/conf.d/wordpress.conf
  notify:
    - Restart Nginx

